[tool.poetry]
name = "pydalio"
version = "0.1.0"
description = ""
authors = ["Tom Laumen <tom.laumen@boskalis.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
typer = "^0.12.5"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
